name: Release

on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    environment: npm
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.LIFEOMIC_NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          yarn install --frozen-lockfile
          yarn lint
          yarn test
          yarn build
          yarn semantic-release
